eureka:
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: messenger

  datasource:
    root-url: jdbc:postgresql://data-base:5432/
#    root-url: jdbc:postgresql://localhost:7777/
    data-base-name: messenger
    url: jdbc:postgresql://data-base:5432/messenger
#    url: jdbc:postgresql://localhost:7777/messenger
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

server:
  port: 80



network_auth_jwt_secret: network_jwt

internal_registration_jwt_secret: internal_registration_jwt
auth_url: http://gateway-server/auth
service_login: messenger
service_password: messenger_password
