version: "3.9"

services:

  result:
    build: ./result

  token-service:
    build: ./tokenService

  database-creator:
    build: ./databaseCreator

  external-request-filter:
    build: ./externalRequestFilter
    depends_on:
      - token-service

  web-api-client:
    build: ./webApiClient
    depends_on:
      - token-service

  data-base:
    build: ./findHataDataBase
    environment:
        - POSTGRES_PASSWORD=postgres
    ports:
        - "7777:5432"

  discovery-server:
    build: ./findHataServerDiscovery
    ports:
        - "8761:8761"

  notification-server:
    build: ./findHataNotificationServer
    environment:
        - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
    depends_on:
      - data-base
      - discovery-server
      - token-service
      - result
      - database-creator
      - external-request-filter

  gateway-server:
    build: ./findHataGateway
    environment:
        - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
    # ports:
        # - "8080:80"
    depends_on:
      - discovery-server
      - web-api-client
      - result

  messaging-server:
    build: ./findHataMessagingServer
    environment:
        - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
#     ports:
#         - "8082:80"
    depends_on:
      - data-base
      - discovery-server
      - web-api-client
      - result
      - database-creator
      - external-request-filter

  proposal-server:
    build: ./findHataProposalServer
    environment:
        - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
        - externalUrl=http://127.0.0.1:8080
        - externalUrlWithoutPort=http://127.0.0.1
        - uploadServerPort=8081
        - externalServiceName=proposals
        - vectorized_service_host=vectorization-server
        - vectorized_service_post=80
        - auth_url=http://gateway-server/auth
    # ports:
        # - "8081:81"
    depends_on:
      - data-base
      - discovery-server
      - result
      - database-creator
      - external-request-filter
      - upload-server

  upload-server:
    build: ./findHataUploadServer
    depends_on:
      - data-base
      - discovery-server
      - result
      - database-creator
      - external-request-filter

  vectorization-server:
    build: ./findHataVectorizationServer
    ports:
        - "9000:80"

  auth-server:
    build: ./findHataAuth
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
      - externalUrl=http://127.0.0.1:8080
      - ngrokMode=true
    depends_on:
      - data-base
      - discovery-server
      - web-api-client
      - result
      - database-creator
      - external-request-filter


  frontend-server:
    build: ./findHataFrontend
    # ports:
      # - "4200:4200"

  ingress:
    build: ./ingress
    ports:
      - "5000:80"
    depends_on:
      - gateway-server
      - frontend-server

  tunnel:
    build: ./ngrok
    ports:
      - "4040:4040"
    environment:
        - NGROK_AUTHTOKEN
    depends_on:
      - ingress
