#!/bin/bash

docker compose down --volumes &&
docker rmi findhata-gateway-server findhata-auth-server findhata-notification-server findhata-discovery-server findhata-data-base findhata-messaging-server findhata-proposal-server findhata-frontend-server findhata-ingress findhata-tunnel
./build_jars &&
docker compose build &&
docker compose up;
