eureka:
  client:
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://discovery-server:8761/eureka/

spring:
  application:
    name: proposals

  datasource:
#    root-url: jdbc:postgresql://localhost:7777/
    root-url: jdbc:postgresql://data-base:5432/
    data-base-name: proposal
#    url: jdbc:postgresql://localhost:7777/proposal
    url: jdbc:postgresql://data-base:5432/proposal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

server:
  port: 80
#  port: 8080



network_auth_jwt_secret: network_jwt

internal_registration_jwt_secret: internal_registration_jwt
#vectorized_service_host: 127.0.0.1
#vectorized_service_post: 9000
#auth_url: http://127.0.0.1:5000/api/auth
service_login: proposal
service_password: proposal_password
