eureka:
  client:
#    enabled: false
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

spring:
  application:
    name: gateway

  cloud:
    gateway:
      default-filters:
        - name: CacheRequestBody
          args:
            bodyClass: java.lang.String
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true


server:
  port: 80

network_auth_jwt_secret: network_jwt

internal_registration_jwt_secret: internal_registration_jwt
auth_url: http://auth-server
service_login: gateway
service_password: gateway_password

